version: '3.8'

services:
  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: style_transfer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # PostgreSQL database (optional, for user data)
  db:
    image: postgres:15-alpine
    container_name: style_transfer_db
    environment:
      POSTGRES_DB: style_transfer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Main application
  app:
    build: .
    container_name: style_transfer_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=docker
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:password@db:5432/style_transfer
      - SECRET_KEY=your-secret-key-here-change-in-production
    volumes:
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./data:/app/data  # Mount audio data directory
    depends_on:
      - redis
      - db
    restart: unless-stopped

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: style_transfer_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL certificates
    depends_on:
      - app
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: