# Enhanced Model Configuration
# Generated by create_basic_models.py

REAL_MODELS_AVAILABLE = True
MODELS_DIR = "checkpoints"

# Model files
MODELS = {
    "folk_to_rock": "checkpoints/folk_to_rock_model.pkl",
    "folk_to_jazz": "checkpoints/folk_to_jazz_model.pkl", 
    "rock_jazz_blend": "checkpoints/rock_jazz_blend_model.pkl",
    "metadata": "checkpoints/model_metadata.pkl"
}

# Enhanced model parameters
MODEL_CONFIG = {
    "version": "1.0.0",
    "enhanced_processing": True,
    "real_time_capable": True,
    "quality_mode": "high"
}
